name: Build and Publish

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, macos-latest]
    
    runs-on: ${{ matrix.os }}

    steps:
      - name: Checkout
        uses: actions/checkout@v2
        
      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 'lts/*'
          cache: 'npm'

      - name: Install Dependencies (Linux)
        run: |
          sudo apt-get install pkg-config build-essential
          sudo apt-get install cmake make
          sudo apt-get install mesa-common-dev libglu1-mesa-dev
        if: matrix.os == 'ubuntu-latest'
      
      - name: Install Dependencies (macOS)
        run: |
          brew install cmake
          brew install make
        if: matrix.os == 'macos-latest'

      - name: Install node dependencies
        run: npm ci
      
      - name: Init packer
        run: npx nodegui-packer --init LookingGlass
      
      - name: Build distributions
        run: npm run build
      
      - name: Release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: npx semantic-release
